#!/bin/bash
set -e
set -o pipefail

npx tsc test/speed-test.process-worker.ts
npx tsc test/speed-test.thread-worker.ts

for i in {1..8}; do
  npx ts-node test/speed-test.master.ts process $i
  npx ts-node test/speed-test.master.ts thread $i
done

